### ISSUE TITLE
Shouldn't this be a rustdoc feature?

### ISSUE THREAD

**Issue by mightyiam** [pnkfelix/tango#23]

**Comment by pnkfelix** [comment]
No, I don't think so?

rustdoc is oriented around documenting public APIs.

Literate programing is about explaining the code implementation itself.

I suppose if the `///` comment form were allowed in arbitrary contexts, then maybe `rustdoc` could be leveraged to handle one direction of the conversion. But attributes on expressions are still experimental, so you cannot just throw `///`'s into the middle of your `fn`-body.

And even if the `///` on expressions issue were resolved, that doesn't resolve the other desirable attribute: Being able to edit the generated markdown file in place, and have it snc back ot the original code. (For more about this, see the feature-set described from my meetup presentation ([slides](http://pnkfx.org/presentations/london-tango-demo/slides.html), [video](https://skillsmatter.com/skillscasts/8372-tango-literate-programming-in-rust)), I don't think we should attempt to get that effect from `rustdoc` alone.
