### ISSUE TITLE
Custom Cargo Watch

### ISSUE THREAD

**Issue by cmgriffing** [pnkfelix/tango#6]
Hi, I apologize if an issue is not really the best place for this but I figured this little thing I did might be useful to you as well as any others that might read this.

I have compiled a custom version of cargo-watch by altering the config here: https://github.com/passcod/cargo-watch/blob/master/src/config.rs
I changed the ignore array to allow non-.rs files. I also increased the timeout, though I'm not sure that was necessary.

Now, I don't have to worry about running `cargo build` when switching from .md to .rs files and vice versa.

**Comment by pnkfelix** [comment]
Hmm that is interesting. Though the link you posted is now dead (d'oh!).

I'm not sure whether to treat this issue as an advertisement for a way to integrate another tool, or as a documentation request, or as pointing out a way to fix an implicit bug...

**Comment by cmgriffing** [comment]
It was this library: https://github.com/passcod/cargo-watch/
However, the author of that is not keen on adding commands to watch non-rust files like the markdown.

For a rust implementation you could try https://github.com/mattgreen/watchexec/ which I have not used. In my case I just used nodemon.

I don't mean for it to be an advertisement for other tools. I just wanted to try and add some info to the possibility of an "auto-compile on change" for Tango.

At this point, documentation pointing out "watch" tools might be useful rather than making one of them part of this implementation. I leave that decision to you.
